<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '(not set)' => '',
    'Account' => '',
    'Account settings' => '',
    'Are you sure to block this user?' => '',
    'Are you sure to confirm this user?' => '',
    'Are you sure to delete this user?' => '',
    'Are you sure to unblock this user?' => '',
    'Block' => '',
    'Block status' => '',
    'Blocked at {0, date, MMMM dd, YYYY HH:mm}' => '',
    'Change your avatar at Gravatar.com' => '',
    'Confirm' => '',
    'Confirmation' => '',
    'Confirmed' => '',
    'Confirmed at {0}' => '',
    'Connect' => '',
    'Create a user account' => '',
    'Disconnect' => '',
    'Information' => '',
    'Manage users' => '',
    'Networks' => '',
    'Profile' => '',
    'Profile settings' => '',
    'Registered at {0} from {1}' => '',
    'Save' => '',
    'Unblock' => '',
    'Update user account' => '',
    'Users' => '',
    'You can connect multiple accounts to be able to log in using them' => '',
    'Зареєстровано ' => '',
];
